package main

import (
	"bytes"
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestCompletionFishOutputsHandWrittenScript 锁住「larkdown completion fish 输出手写脚本、
// 而非 urfave/cli 自动生成版」这一公开行为。urfave/cli 若再升级改 completion 命令的子命令结构，
// 此测试会立即失败。
func TestCompletionFishOutputsHandWrittenScript(t *testing.T) {
	cmd := newRootCommand()
	var buf bytes.Buffer
	cmd.Writer = &buf

	err := cmd.Run(context.Background(), []string{"larkdown", "completion", "fish"})
	require.NoError(t, err)

	out := buf.String()
	assert.Contains(t, out, "# Fish completions for larkdown") // 手写版标志
	assert.NotContains(t, out, "auto-generated by")            // 确认不是 urfave 自动版
}
